/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package modelo.vista;

import modelo.beans.User;
import modelo.CRUD.Crud;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author genca
 */
public class LoginForm extends javax.swing.JPanel {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        enterButtonField = new javax.swing.JButton();
        registerButtonField = new javax.swing.JButton();
        titleLogin = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        userNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(0, 204, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        enterButtonField.setBackground(new java.awt.Color(0, 102, 102));
        enterButtonField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        enterButtonField.setForeground(new java.awt.Color(255, 255, 255));
        enterButtonField.setText("Entrar");
        enterButtonField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enterButtonField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enterButtonField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonFieldActionPerformed(evt);
            }
        });

        registerButtonField.setBackground(new java.awt.Color(0, 102, 102));
        registerButtonField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        registerButtonField.setForeground(new java.awt.Color(255, 255, 255));
        registerButtonField.setText("Resgistrarse");
        registerButtonField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerButtonField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButtonField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonFieldActionPerformed(evt);
            }
        });

        titleLogin.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        titleLogin.setForeground(new java.awt.Color(0, 102, 102));
        titleLogin.setText("LOGIN");

        passwordField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(0, 102, 102));
        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        userNameField.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        userNameField.setForeground(new java.awt.Color(0, 102, 102));
        userNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameField.setAlignmentY(100.0F);
        userNameField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Nombre de usuario");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Contrasena");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterButtonField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(registerButtonField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titleLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterButtonField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButtonField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonFieldActionPerformed
        // TODO add your handling code here:
        RegisterForm registerForm = new RegisterForm();

    // Establecer la ventana de inicio de sesión (LoginForm) como el padre de la ventana de registro (RegisterForm)
    JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    JDialog dialog = new JDialog(parentFrame, "Registrar Usuario", true);
    dialog.setContentPane(registerForm);
    dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    dialog.pack();
    dialog.setLocationRelativeTo(null);

    // Mostrar la ventana de registro
    dialog.setVisible(true);
    }//GEN-LAST:event_registerButtonFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void enterButtonFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonFieldActionPerformed
        // TODO add your handling code here:
        UsersTable usersTable = new UsersTable(); // Variable para mantener una referencia a UsersTable
        String userName = userNameField.getText();
        String password = new String(passwordField.getPassword());

        List<User> userList = Crud.getUsers();

    boolean userFound = false;
        for (User user : userList) {
            if (user.getUserName().equals(userName) && user.getPassword().equals(password)) {
                userFound = true;
                break;
            }
        }

        if (userFound) {
            // Usuario y contraseña son correctos
            // Aquí puedes mostrar la ventana de la aplicación o realizar otras acciones necesarias
            System.out.println("Usuario y contraseña son correctos");

            // Crear la ventana UsersTable si aún no existe
            if (usersTable == null) {
                usersTable = new UsersTable();
            }

            // Obtener el JFrame padre actual
            JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

            // Cerrar la ventana de inicio de sesión
            parentFrame.dispose();

            // Mostrar la ventana UsersTable
            JFrame usersTableFrame = new JFrame("Usuarios Registrados");
            usersTableFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            usersTableFrame.setContentPane(usersTable);
            usersTableFrame.pack();
            usersTableFrame.setLocationRelativeTo(null);
            usersTableFrame.setVisible(true);
        } else {
            // Usuario y/o contraseña incorrectos
            mostrarMensajeError("Usuario y/o contraseña incorrectos");
        }
    
    }//GEN-LAST:event_enterButtonFieldActionPerformed
   
    // Mostrar un mensaje de error
    private void mostrarMensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enterButtonField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registerButtonField;
    private javax.swing.JLabel titleLogin;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
